package be.nille.ci;


import be.nille.blog.component.navigation.Blog;
import lombok.extern.slf4j.Slf4j;
import static spark.Spark.get;
import static spark.Spark.port;
import static spark.Spark.staticFiles;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
@Slf4j
public class App {

    public static void main(String[] args) throws Exception {
        ServerPort port = new SimpleServerPort(System.getenv("PORT"));

        port(port.getValue());

        staticFiles.location("/public");
        log.debug("Mongo URL: " + System.getenv("MONGO_URL"));
        

        get("/", (request, response) -> {
    
            IndexPage page = new IndexPage(new Blog("Nille.be"));
            return page.handleRequest(request, response);

        });

    }

}
