package be.nille.ci;


import be.nille.blog.component.navigation.Blog;
import static spark.Spark.get;
import static spark.Spark.port;
import static spark.Spark.staticFiles;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) throws Exception {
        ServerPort port = new SimpleServerPort(System.getenv("PORT"));

        port(port.getValue());

        staticFiles.location("/public");

        get("/*", (request, response) -> {
    
            IndexPage page = new IndexPage(new Blog("Nille.be"));
            return page.handleRequest(request, response);

        });

    }

}
