package be.nille.ci;

import static spark.Spark.get;
import static spark.Spark.port;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        port(80);
        get("/hello", (req, res) -> new App().getGreeting());
    }
}
