package be.nille.ci;

import org.takes.facets.fork.FkRegex;
import org.takes.facets.fork.TkFork;
import org.takes.http.Exit;
import org.takes.http.FtBasic;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) throws Exception {
        ServerPort port = new SimpleServerPort(System.getenv("PORT"));
        
        new FtBasic(
                new TkFork(new FkRegex("/", "hello, world!")), port.getValue()
        ).start(Exit.NEVER);
    }
}
