package be.nille.blog;

import be.nille.blog.component.Page;
import be.nille.blog.component.Template;
import be.nille.blog.component.home.HomePage;
import be.nille.blog.component.home.HomeTemplate;
import be.nille.blog.dal.Posts;
import be.nille.blog.dal.mongo.MgPosts;
import be.nille.blog.config.ServerPort;
import be.nille.blog.config.SimpleServerPort;
import com.mongodb.MongoClient;
import com.mongodb.MongoClientURI;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import lombok.extern.slf4j.Slf4j;
import org.bson.Document;
import static spark.Spark.get;
import static spark.Spark.port;
import static spark.Spark.staticFiles;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
@Slf4j
public class App {

    private final String databaseURL;

    public App(final String databaseURL) {
        this.databaseURL = databaseURL;
    }

    public MongoDatabase getDatabase() {
        
        MongoClient mongoClient = new MongoClient(
                new MongoClientURI(databaseURL)
        );
        MongoDatabase db = mongoClient.getDatabase("openid-connect");
        return db;
    }

    public static void main(String[] args) throws Exception {
        ServerPort port = new SimpleServerPort(System.getenv("PORT"));
        port(port.getValue());
        staticFiles.location("/public");
        
        App app = new App(System.getenv("MONGO_URL"));

        get("/", (request, response) -> {
            Page page = new HomePage(app.getDatabase());
            return page.handleRequest();
            }
        );

    }

}
