package be.nille.blog;

import be.nille.blog.component.post.PostCommentRequest;
import be.nille.blog.config.ServerPort;
import be.nille.blog.config.SimpleServerPort;
import com.mongodb.MongoClient;
import com.mongodb.MongoClientURI;
import com.mongodb.client.MongoDatabase;
import lombok.extern.slf4j.Slf4j;
import spark.Route;
import spark.Service;
import static spark.Spark.port;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
@Slf4j
public class ServiceApp {

    private final String databaseURL;

    public ServiceApp(final String databaseURL) {
        this.databaseURL = databaseURL;
    }

    public MongoDatabase getDatabase() {

        MongoClient mongoClient = new MongoClient(
                new MongoClientURI(databaseURL)
        );
        MongoDatabase db = mongoClient.getDatabase("openid-connect");
        return db;
    }

    public static void main(String[] args) throws Exception {
        ServerPort port = new SimpleServerPort(System.getenv("PORT"));
        


        Service service = Service.ignite();
     
        service.staticFileLocation("/public");
        service.port(port.getValue());
  
        
        Route route = (request, response) -> {
            PostCommentRequest pcr = new PostCommentRequest(request);
            return pcr.toString();
        };
       
        service.post("posts/:id", route);

    }

}
